---

  - name: "Subscribe the system"
    include_tasks: subscribe.yaml
    tags: ['subscribe']

  - name: "Enable only the RHEL7 repos"
    include_tasks: repos.yaml
    tags: ['repos']

  - name: "Add hosts line"
    include_tasks: hosts.yaml
    tags: ['hosts']

  - name: "Configure DHCP server"
    include_tasks: dhcpd.yaml
    tags: ['dhcpd']

  - name: "Configure HTTPD server"
    include_tasks: httpd.yaml
    tags: ['httpd','mount']