---
# Simple playbook that connects to the target system as root, but
# then creates and ansible user and group. Copies a local ssh public key
# then adds to sudo e.t.c.
#
# This means we can now connect as the ansible user for the proper playbook.

- name: Attempt to standardise the RHEL system
  hosts:  all
  remote_user: root
  tasks:
    - name: Create the Ansible group
      group:
        name: ansible
        state: present
        gid: 1337

    - name: Create the Ansible user and generate it's SSH key.
      user:
        name: ansible
        comment: "Ansible service account"
        uid: 1337
        group: ansible
        generate_ssh_key: yes
        state: present


    - name: Add sudoers users to wheel group
      user:
        name: "ansible"
        groups: wheel
        append: yes

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Copy local ssh public key in place
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
